# Site settings
title: The Life of Danny
description: My personal portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Danny Tu
user_description: I'm Danny, nice to meet you! I'm a big computer nerd and the person my parents go to when the internet is slow. I graduated with a Bachelor's in Mathematics at George Mason University and am always looking to continue learning and developing my data analyst skillset. I'm passionate about applications in machine learning, data analysis and visualization, and have experience as pseudo network and sysadmin for my home lab.
user_title: Tech Nerd, Food Motivated, Wushu Master
email:  Tu.Danny2@gmail.com

# Google-analytics
google-analytics:
  id: "G-KT417PYBXW"

exclude: ['package.json', 'src' , 'node_modules']
